import Head from 'next/head'
import Navbar from '../src/components/Navbar/TopHeader'
import TopHeader from '../src/components/TopHeader/TopHeader'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <Navbar></Navbar>
        <TopHeader></TopHeader>
    </div>
  )
}
